server:
  port: 8082
spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true
    config:
      discovery:
        service-id: bing-config
        enabled: true
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    enabled: true

